categories_cible:
  default: ""
  type: list
  description: >
    Liste des slugs de catégories (séparés par |) pour lesquelles la liste
    des sujets sera triée par titre (A→Z).
    Exemple : docs|faq|ressources
  refresh: true
